### ISSUE TITLE
No module named 'robot_properties_solo.utils'

### ISSUE THREAD

**Issue by emrecemal** [open-dynamic-robot-initiative/robot_properties_solo#51]
Hello,

I just installed all the related dependencies, but I get an import error when I try to run demo_simulate_solo8.py

$ python robot_properties_solo/demos/demo_simulate_solo8.py
pybullet build time: Dec 10 2021 10:04:01
/Users/emrecemal/miniconda3/lib/python3.8/site-packages/pinocchio/shortcuts.py:45: UserWarning: You passed package dir(s) via argument geometry_model and provided package_dirs.
  geom_model = pin.buildGeomFromUrdf(model, filename, geometry_type, package_dirs)
Traceback (most recent call last):
  File "tesst.py", line 16, in <module>
    from robot_properties_solo.solo8wrapper import Solo8Robot, Solo8Config
  File "/Users/emrecemal/miniconda3/lib/python3.8/site-packages/robot_properties_solo/solo8wrapper.py", line 17, in <module>
    from robot_properties_solo.utils import find_paths
ModuleNotFoundError: No module named 'robot_properties_solo.utils'

**Comment by egordv** [comment]
Hello @emrecemal 
Same error, as a quick fix I commented https://github.com/open-dynamic-robot-initiative/robot_properties_solo/blob/e917f77f538c4f2725f170618bb65a42804bc296/src/robot_properties_solo/solo8wrapper.py#L17 this line and this solved the issue (don't forget to reinstall the package)

**Comment by HuShanzhi** [comment]
hi, I also encountered this problem.

**reason:**
In the [robot_properties_solo/src/robot_properties_solo](https://github.com/open-dynamic-robot-initiative/robot_properties_solo/tree/master/src/robot_properties_solo) directory, there is no "utils.py" file.

**solution:**
1. Copy file [utils.py](https://github.com/open-dynamic-robot-initiative/robot_properties_solo/blob/a13dee08aec2579d059ed2ad4e0413062a7c9af2/src/robot_properties_solo/utils.py) to your local directory "/home/user/bullet_utils/robot_properties_solo/src/robot_properties_solo".
2. Enter the directory "robot_properties_solo" by using the command `cd bullet_utils/robot_properties_solo`, and then run the command `pip3 install .` again.
